### PR TITLE
Fix issues with "till next achievement"

### LINKED ISSUE #797: Left till next achivment instable color green
**Describe the bug**
When there is 1 building left ttill achivment, and it's the best building (green),
then the tooltip for left till achivment flickers between blue and green.

I also seen the it being yellow for 10x when the building is green in the 10x mode.

**To Reproduce**
The steps needed to reproduce the behavior:
1. Play until a building with 1 building left to achivment is green. (or use savefile)
2. Look at the tooltip
3. (Maybe related to not afording that building at the moment)

**Screenshots**

**Save file**
[SundragonCookiesBakery.txt](https://github.com/CookieMonsterTeam/CookieMonster/files/6411145/SundragonCookiesBakery.txt)

**Browser**
Wind10, Chrome v90.0.4430.93
&
Win10, Firefox v88

### LINKED ISSUE #800: Left till next achievement does not reset correctly after obtaining an achievement
**Describe the bug**
I think I just noticed that when building A reports x till next achievement and you obtain that achievement buying a number of buildings of building B the tooltip for building A does not update correctly.

### LINKED ISSUE #801: left till next achivement appears on buildings with all achivements after purchasing
1. load a save file with more than 600 of a building (or 800 for cursors)
2. buy another building
3. buildings left til next achivement shows up on the building, despite having all achivements

screenshot after purchasing:
Screenshot from 2021-05-05 10-50-50

**Save file**
```
Mi4wMzF8fDE2MTgzNzAzNzgwNzE7MTYxNDMxNDExMjQ1NjsxNjIwMjIzODc1MTY5O0Nsb251cztvdmJ1c3wxMTExMTEwMTExMDEwMDEwMDEwMTB8MS40MzY0MDA4NTU5MjQ1ODI4ZSs1MjszLjMyMTU1ODgyNjgxNTkyM2UrNTM7MzM0Nzs1MDAwOzUuMTE2MjE2NTgyNDQ4Njc4ZSs1MjsxMjI4MTsxOzA7Ny4xMDg5ODI0OTM0Nzk5MjFlKzUyOzM7Mjg7MDswOy0xOzMxOzMyMDsxLjU5OTA5NjUwODg4MDMzNDdlKzUyOzk3ODsxNDs0NDstMTs0Ozs3LjA0NDY1MDk3OTc1NDY2MmUrNTE7MTI7NDE0MjU2MzI1MTQ4Mjk7MzkxODgzODQ3Mzg3Mzc7MjIzNzI0Nzc3NjA5MjswOzA7MjI2OzY0MTs2MTM7NjUzOzIyMjsyNTsxNTsxNzswOzUwOzA7MDsxMjs5ODsxNjIwMjA4OTM0Mjc2OzA7MDsyMjcsMCwxMjksMSwyOzQxOzE7MTsxLjE4NDk2ODcyMjQwNjkzNThlKzQ2O3w4MTYsMTgyNiwyLjYwMDg3MTgyMjM1NjM2OTRlKzUwLDgsLDAsODE2OzgxNSwxMTcwLDIuMjQ2NzU5MDg1NjE5NzM1N2UrNTAsMCwsMSw4MTU7NzQ4LDExMDAsOC4yNjA3MTM0Mjk2MTY2MDNlKzQ2LDksMTYyMDIyNDY4NDQyMzoyOjE2MTk5MTMxMjk2ODg6MDo2NToxNDI3OjA6MToxNjE4MzcwMzc4MDk1OiAxMTExMTAxMTExMTExMTExMTExMTEwMTExMTExMTExMTExIDE4OjUyOjE4OjU1OjE4OjU1OjE4OjY1OjE4OjQ4OjE4OjUyOjE4OjUwOjE4OjU0OjE4OjQ0OjE4OjUwOjE4OjQ5OjE4OjU4OjE4OjUxOjE4OjQ3OjE4OjUwOjE4OjUwOjE4OjUwOjE4OjQ3OjE4OjU0OjE4OjM4OjE4OjQ4OjE4OjU1OjE4OjU3OjE4OjQ4OjE4OjQ1OjE4OjQ2OjE4OjQ0OjE4OjU0OjE4OjU3OjE4OjYyOjE4OjQ4OjE4OjQ0OjE4OjY0OjE4OjQyOjE4OjUwOjE4OjQ3OiwwLDc0ODs3MzMsMTA4Myw3LjE2NDgwNzQ0OTczNDkxN2UrNDgsMCwsMSw3MzM7NzE0LDEwNjQsOC45NTAwMTMwNjk2NTM3MjRlKzQ3LDAsLDEsNzE0OzY5NywxMDQ3LDEuOTA1ODA0NjAzMTk1NTMxOGUrNDcsMSwzOjgyOjE6MjkxNTI4MS44MDg4NzQ0NzY3OjA6IDgwNDoyOi0xOTo3MzY6OTg3OjA6MCEzNDI6NDotODQ6ODc6ODgyOjA6MCE4MTk6MjotNTk6NDcwOjA6MDowITQwMDE6NTotNTg6MTU3Ojg1NjowOjAhODAzMDo1OjI1OjcwODowOjA6MCEzMjg2OjI6LTUyOjU1Nzo4Mjc6MDowITQyODE6MjotNDU6NDk4OjA6MDowITc3ODA6MDoxMTo5ODowOjA6MCE3ODI2OjU6LTgzOjU5Nzo3Njc6MDowITM2MTk6NDotMTY1OjcyMTowOjA6MCE5ODcyOjI6LTIzOjcwOTowOjA6MCE1NTU6NDotMTY0OjQ2MDo3MjM6MDowITEwMTA1OjI6LTUwOjYzNDowOjA6MCExMzExMTo1Oi02OToxMzowOjA6MCExNjEzODoxOjIxOjQ0OjA6MDowITg4Njk6NDotMTY5OjcwOjY1MDowOjAhIDAsMCw2OTc7Njc4LDEwMjgsOC40Nzk4ODAyMDM0NjkyMjVlKzQ3LDEsOC8wLzcgMiAxNjIwMjIwMzI0MzI3IDAsMCw2Nzg7NjU4LDE1MTgsMi40NDUyNDE1MjUzMDE2NTkzZSs0NywyLDExMCAxNzkgNzY2IDAsMCw2NTg7NjM4LDk4OCw2Ljg3MjY3NzQ0NjA5OTkwNGUrNDYsMCwsMSw2Mzg7NjE5LDk2OSwzLjU4NzkwNjMwNDk1MjExODdlKzQ3LDAsLDEsNjE5OzYxOCw5NjgsNS40NTUxODc5NzUzNzQ5ODllKzQ5LDAsLDEsNjE4OzU4Niw5MzYsMS4yMzY1MTc2MjUwNzk3NzkxZSs0OSwwLCwxLDU4Njs1ODAsOTMwLDEuMjE4MjY2NTYxMDA5MzUwNmUrNTAsMCwsMSw1ODA7NjAwLDk1MCw3LjAzOTc2MzI2NjMwNTczNWUrNTAsMCwsMSw2MDA7NTYyLDkxMiwxLjY5MzUxOTcxNzIyNjg4OGUrNTEsMCwsMSw1NjI7NTU4LDkwOCwxLjE4NTE3ODE1MjM2NzY5NWUrNTIsMCwsMSw1NTg7NTEwLDg2MCwyLjc2NDU2NDgyOTAyOTc5MDNlKzUxLDAsLDEsNTEwOzUwMCw4NTIsOS41OTIxMTc2NzAwNTUxOThlKzUxLDAsLDEsNTAwO3wxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMTExMTExMTAwMTExMTExMDAxMDAwMTExMTExMTExMTAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMDEwMTAwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMTAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMTExMTExMTExMTEwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAxMTExMTExMTExMTExMTExMTExMTEwMTAwMDAwMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDAwMDAwMDAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMTExMTExMTAwMDAwMDAwMTExMTExMTF8MTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMTExMTExMTExMTExMTAxMTExMTExMDAwMDAwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMTExMTAxMTAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMDAwMDAwMDAwMDAwMTEwMTExMTExMTExMTExMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMTExMTExMTExMTExMTExMTExMDExMTExMDEwMTExMDAxMTAwMTAxMTEwMDAxMTExMTExMTExMTExMTExMTAwMTExMTExMTExMTExMTEwMDAxMTExMTExMTExMTAwMTExMDExMTEwMTAwMDAwMHx8Q29va2llTW9uc3Rlcjp7ImZhdm91cml0ZVNldHRpbmdzIjpbXSwic2V0dGluZ3MiOnsiQm90QmFyIjoxLCJUaW1lckJhciI6MSwiVGltZXJCYXJQb3MiOjAsIlRpbWVyQmFyT3ZlcmxheSI6MiwiQnVpbGRDb2xvciI6MSwiUFBEaXNwbGF5VGltZSI6MCwiVXBCYXJDb2xvciI6MSwiVXBncmFkZUJhckZpeGVkUG9zIjoxLCJDYWxjV3JpbmsiOjAsIkNQU01vZGUiOjAsIkF2Z0NQU0hpc3QiOjYsIkF2Z0NsaWNrc0hpc3QiOjAsIlBQRXhjbHVkZVRvcCI6MCwiUFBSaWdpZGVsTW9kZSI6MCwiUFBTZWNvbmRzTG93ZXJMaW1pdCI6MCwiUFBPbmx5Q29uc2lkZXJCdXlhYmxlIjowLCJUb29sV2FybkJvbiI6MSwiVGl0bGUiOjEsIkdlbmVyYWxTb3VuZCI6MSwiR0NOb3RpZmljYXRpb24iOjAsIkdDRmxhc2giOjEsIkdDU291bmQiOjEsIkdDVm9sdW1lIjoxMDAsIkdDU291bmRVUkwiOiJodHRwczovL2ZyZWVzb3VuZC5vcmcvZGF0YS9wcmV2aWV3cy82Ni82NjcxN185MzE2NTUtbHEubXAzIiwiRm9ydHVuZU5vdGlmaWNhdGlvbiI6MCwiRm9ydHVuZUZsYXNoIjowLCJGb3J0dW5lU291bmQiOjEsIkZvcnR1bmVWb2x1bWUiOjEwMCwiRm9ydHVuZVNvdW5kVVJMIjoiaHR0cHM6Ly9mcmVlc291bmQub3JnL2RhdGEvcHJldmlld3MvMTc0LzE3NDAyN18zMjQyNDk0LWxxLm1wMyIsIlNlYU5vdGlmaWNhdGlvbiI6MCwiU2VhRmxhc2giOjAsIlNlYVNvdW5kIjowLCJTZWFWb2x1bWUiOjEwMCwiU2VhU291bmRVUkwiOiJodHRwczovL3d3dy5mcmVlc291bmQub3JnL2RhdGEvcHJldmlld3MvMTIxLzEyMTA5OV8yMTkzMjY2LWxxLm1wMyIsIkdhcmRGbGFzaCI6MCwiR2FyZFNvdW5kIjowLCJHYXJkVm9sdW1lIjoxMDAsIkdhcmRTb3VuZFVSTCI6Imh0dHBzOi8vZnJlZXNvdW5kLm9yZy9kYXRhL3ByZXZpZXdzLzEwMy8xMDMwNDZfODYxNzE0LWxxLm1wMyIsIk1hZ2ljTm90aWZpY2F0aW9uIjowLCJNYWdpY0ZsYXNoIjowLCJNYWdpY1NvdW5kIjowLCJNYWdpY1ZvbHVtZSI6MTAwLCJNYWdpY1NvdW5kVVJMIjoiaHR0cHM6Ly9mcmVlc291bmQub3JnL2RhdGEvcHJldmlld3MvMjIxLzIyMTY4M18xMDE1MjQwLWxxLm1wMyIsIldyaW5rbGVyTm90aWZpY2F0aW9uIjowLCJXcmlua2xlckZsYXNoIjowLCJXcmlua2xlclNvdW5kIjowLCJXcmlua2xlclZvbHVtZSI6MTAwLCJXcmlua2xlclNvdW5kVVJMIjoiaHR0cHM6Ly9mcmVlc291bmQub3JnL2RhdGEvcHJldmlld3MvMTI0LzEyNDE4Nl84MDQzLWxxLm1wMyIsIldyaW5rbGVyTWF4Tm90aWZpY2F0aW9uIjowLCJXcmlua2xlck1heEZsYXNoIjowLCJXcmlua2xlck1heFNvdW5kIjoxLCJXcmlua2xlck1heFZvbHVtZSI6MTAwLCJXcmlua2xlck1heFNvdW5kVVJMIjoiaHR0cHM6Ly9mcmVlc291bmQub3JnL2RhdGEvcHJldmlld3MvMTUyLzE1Mjc0M18xNTY2My1scS5tcDMiLCJUb29sdGlwQnVpbGRVcGdyYWRlIjoxLCJUb29sdGlwQW1vciI6MCwiVG9vbFdhcm5MdWNreSI6MSwiVG9vbFdhcm5MdWNreUZyZW56eSI6MSwiVG9vbFdhcm5Db25qdXJlIjoxLCJUb29sV2FybkNvbmp1cmVGcmVuenkiOjEsIlRvb2xXYXJuRWRpZmljZSI6MSwiVG9vbFdhcm5Vc2VyIjowLCJUb29sV2FyblBvcyI6MSwiVG9vbHRpcEdyaW0iOjEsIlRvb2x0aXBXcmluayI6MSwiVG9vbHRpcEx1bXAiOjEsIlRvb2x0aXBQbG90cyI6MSwiVG9vbHRpcFBhbnRoZW9uIjoxLCJEcmFnb25BdXJhSW5mbyI6MSwiVG9vbHRpcEFzY2VuZEJ1dHRvbiI6MSwiU3RhdHMiOjEsIk1pc3NpbmdVcGdyYWRlcyI6MSwiVXBTdGF0cyI6MSwiVGltZUZvcm1hdCI6MCwiRGV0YWlsZWRUaW1lIjoxLCJHcmltb2lyZUJhciI6MSwiSGVhdmVubHlDaGlwc1RhcmdldCI6MSwiU2hvd01pc3NlZEdDIjowLCJTY2FsZSI6MiwiU2NhbGVEZWNpbWFscyI6MiwiU2NhbGVTZXBhcmF0b3IiOjAsIlNjYWxlQ3V0b2ZmIjo5OTk5OTksIlNvcnRCdWlsZGluZ3MiOjAsIlNvcnRVcGdyYWRlcyI6MCwiR0NUaW1lciI6MSwiRmF2aWNvbiI6MSwiV3JpbmtsZXJCdXR0b25zIjoxLCJIaWRlU2VjdGlvbnNCdXR0b25zIjowLCJCdWxrQnV5QmxvY2siOjAsIkhlYWRlciI6eyJCYXJzQ29sb3JzIjoxLCJDYWxjdWxhdGlvbiI6MSwiTm90aWZpY2F0aW9uIjoxLCJOb3RpZmljYXRpb25HZW5lcmFsIjoxLCJOb3RpZmljYXRpb25HQyI6MSwiTm90aWZpY2F0aW9uRkMiOjEsIk5vdGlmaWNhdGlvblNlYSI6MSwiTm90aWZpY2F0aW9uR2FyZCI6MSwiTm90aWZpY2F0aW9uTWFnaSI6MSwiTm90aWZpY2F0aW9uV3JpbmsiOjEsIk5vdGlmaWNhdGlvbldyaW5rTWF4IjoxLCJUb29sdGlwIjoxLCJTdGF0aXN0aWNzIjoxLCJOb3RhdGlvbiI6MSwiTWlzY2VsbGFuZW91cyI6MSwiTHVja3kiOjEsIkNoYWluIjoxLCJTcGVsbHMiOjEsIkdhcmRlbiI6MSwiUHJlc3RpZ2UiOjEsIldyaW5rIjoxLCJTZWEiOjEsIk1pc2MiOjEsIkluZm9UYWIiOjEsIkZhdm91cml0ZSI6MSwiQ29sb3VycyI6MSwiQmFyc0Rpc3BsYXkiOjF9LCJCdWlsZENvbG91ciI6MSwiQ29sb3VyQmx1ZSI6IiM0YmI4ZjAiLCJDb2xvdXJHcmVlbiI6IiMwMGZmMDAiLCJDb2xvdXJZZWxsb3ciOiIjZmZmZjAwIiwiQ29sb3VyT3JhbmdlIjoiI2ZmN2YwMCIsIkNvbG91clJlZCI6IiNmZjAwMDAiLCJDb2xvdXJQdXJwbGUiOiIjZmYwMGZmIiwiQ29sb3VyR3JheSI6IiNiM2IzYjMiLCJDb2xvdXJQaW5rIjoiI2ZmMTQ5MyIsIkNvbG91ckJyb3duIjoiIzhiNDUxMyIsIlVwQmFyQ29sb3VyIjoxLCJNaXNzaW5nQWNoaWV2ZW1lbnRzIjowLCJDb2xvdXJHQ0ZsYXNoIjoiI2ZmZmZmZiIsIkNvbG91ckZvcnR1bmVGbGFzaCI6IiNmZmZmZmYiLCJDb2xvdXJTZWFGbGFzaCI6IiNmZmZmZmYiLCJDb2xvdXJHYXJkRmxhc2giOiIjZmZmZmZmIiwiQ29sb3VyTWFnaWNGbGFzaCI6IiNmZmZmZmYiLCJDb2xvdXJXcmlua2xlckZsYXNoIjoiI2ZmZmZmZiIsIkNvbG91cldyaW5rbGVyTWF4Rmxhc2giOiIjZmZmZmZmIiwiRmF2b3VyaXRlU2V0dGluZ3MiOjEsIlVwZ3JhZGVzTmV2ZXJDb2xsYXBzZSI6MH0sInZlcnNpb24iOiIyLjAzMS44In07%21END%21
```
**Browser**
Firefox 88.0

### PR DESCRIPTION
**Pull request by DanielNoord**
This closes #801, closes #800, closes #797

### CODE REVIEW

File: src/Cache/TillNextAchievement/AllAmountTillNextAchievement.js [hunk 1]
```diff
@@ -1,23 +1,34 @@
...
+          CacheObjectsNextAchievement[i].TotalNeeded - Game.Objects[i].amount,
+        ),
       };
     } else {
       const tillNext = IndividualAmountTillNextAchievement(i);
       result[i] = {
         AmountNeeded: tillNext,
         TotalNeeded: Game.Objects[i].amount + tillNext,
+        price: Game.Objects[i].getSumPrice(
+          Game.Objects[i].amount + tillNext - Game.Objects[i].amount,
```
Comment (puggan) [inline src/Cache/TillNextAchievement/AllAmountTillNextAchievement.js:30]: Looks like `A + B - A` could be simplified to just B, or in this case just tillNext

Comment (DanielNoord) [reply src/Cache/TillNextAchievement/AllAmountTillNextAchievement.js:30]: Oh lol, that's a stupid mistake..
Will fix for next release!
